name: Deploy to NuxtHub
on: push
env:
  BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  
  NUXT_HUB_PROJECT_KEY: ${{ vars.NUXT_HUB_PROJECT_KEY }}
  FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
  FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}}}
  FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
  FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
  FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID}}

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Ensure NuxtHub module is installed
        run: npx nuxthub@latest ensure

      - name: Build application
        run: pnpm build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: ohlaw-mstools-2-v83e
